#!/bin/bash
# FROM https://github.com/stigi/dockerfile-postgresql/blob/master/start
# LICENSE MIT https://github.com/stigi/dockerfile-postgresql/blob/master/LICENSE

DATADIR="/var/lib/postgresql/data"
CONF="/etc/postgresql-common/postgresql.conf"
POSTGRES="/usr/local/lib/postgresql/bin/postgres"
INITDB="/usr/local/lib/postgresql/bin/initdb"

# test if DATADIR is existent
if [ ! -d $DATADIR ]; then
  echo "Creating Postgres data at $DATADIR"
  mkdir -p $DATADIR
fi

# test if DATADIR has content
if [ ! "$(ls -A $DATADIR)" ]; then
  echo "Initializing Postgres Database at $DATADIR"
  chown -R postgres $DATADIR
  su postgres sh -c "$INITDB $DATADIR"
  su postgres sh -c "$POSTGRES --single -D $DATADIR -c config_file=$CONF" <<< "CREATE USER $USERNAME WITH SUPERUSER PASSWORD '$PASS';"
fi

trap "echo \"Sending SIGTERM to postgres\"; killall -s SIGTERM postgres" SIGTERM

su postgres sh -c "$POSTGRES -D $DATADIR -c config_file=$CONF" &

wait $!

# vim: set filetype=bash
