session_name: docker
windows:
- layout: 6da5,239x56,0,0[239x34,0,0,65,239x21,0,35{119x21,0,35,66,119x21,120,35,67}]
  options:
    automatic-rename: 'off'
  start_directory: ./
  panes:
  - vim
  - pane
  - pane
  window_name: sys
- layout: 6da5,239x56,0,0[239x34,0,0,65,239x21,0,35{119x21,0,35,66,119x21,120,35,67}]
  options:
    automatic-rename: 'off'
  start_directory: ./postgres
  panes:
  - vim
  - pane
  - pane
  window_name: postgres
